version: '3'

services:
  node1:
    image: "node-app:latest"
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
      - 8090:8090
    networks:
      dae:
        ipv4_address: 172.1.0.10

  promoetheus:
    image: prom/prometheus:v2.20.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - node1
    networks:
      dae:
        ipv4_address: 172.1.0.11

  grafana:
    image: grafana/grafana:7.1.5
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - 3000:3000
    depends_on:
      - promoetheus
    networks:
      dae:
        ipv4_address: 172.1.0.12

networks:
  dae:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/24
