global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "express-health-check-demo"
    metrics_path: "/prometheus"
    static_configs:
      # - targets: ["docker.for.mac.host.internal:8090"]
      - targets: ["172.1.0.10:8090"]
